function [cmap] = build_monochrome( monochrome_bins, gradient_bins, concentration, ...
                                    very_light_c, light_c, c, dark_c, very_dark_c, base)
    cmap = build_colormap(monochrome_bins, 100, ...
        ...
               [dark_c       dark_c light_c dark_c dark_c; ...
                very_light_c base   base    base   very_light_c;       ...
        repmat([very_light_c base   base    base   very_light_c],      ...
        ...
        concentration, 1 )]);
end
